---
extends: [airbnb, plugin:flowtype/recommended]
env:
  node: true
  es6: true
  browser: true
globals:
  require: true
  config: true
  __DEV__: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react, flowtype]

rules:
  max-len: [1, 140, 2, {"ignoreUrls":true}]
  comma-dangle: [error, never]
  no-console: [error, allow: [warn, error, info]]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  react/forbid-prop-types: 0
  arrow-parens: 0
  no-underscore-dangle: 0
  quotes: ["error", "double", { "avoidEscape": true }]
  jsx-a11y/aria-role: 0
  global-require: 0
  arrow-body-style: 0
  import/no-named-as-default-member: 0
  react/jsx-wrap-multilines: ["error", {arrow: false}]
  react/no-array-index-key: 0
  react/sort-comp: ['error', { order: [ 'type-annotations', 'static-methods', 'lifecycle', '/^on.+$/', '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/', 'everything-else', '/^render.+$/', 'render' ] }]
