// flow-typed signature: 3a5b3373bc35eb065f360c16e55aea16
// flow-typed version: <<STUB>>/react-moment-proptypes_v^1.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-moment-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-moment-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-moment-proptypes/src/index' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/src/moment-validation-wrapper' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/setup' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-moment-proptypes/src/index.js' {
  declare module.exports: $Exports<'react-moment-proptypes/src/index'>;
}
declare module 'react-moment-proptypes/src/moment-validation-wrapper.js' {
  declare module.exports: $Exports<'react-moment-proptypes/src/moment-validation-wrapper'>;
}
declare module 'react-moment-proptypes/test/setup.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/setup'>;
}
declare module 'react-moment-proptypes/test/test.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/test'>;
}
